import {Countries} from './Country.model';

export var countries: Countries [] = [
  { code: "CH", name: "Schweiz", number: "756" },
  { code: "DE", name: "Deutschland", number: "276" },
  { code: "FR", name: "Frankreich", number: "250" },
  { code: "AF", name: "Afghanistan", number: "004" },
  { code: "EG", name: "Ägypten", number: "818" },
  { code: "AL", name: "Albanien", number: "008" },
  { code: "DZ", name: "Algerien", number: "012" },
  { code: "AD", name: "Andorra", number: "020" },
  { code: "AO", name: "Angola", number: "024" },
  { code: "AI", name: "Anguilla", number: "660" },
  { code: "AG", name: "Antigua und Barbuda", number: "028" },
  { code: "GQ", name: "Äquatorialguinea", number: "226" },
  { code: "AR", name: "Argentinien", number: "032" },
  { code: "AM", name: "Armenien", number: "051" },
  { code: "AZ", name: "Aserbaidschan", number: "031" },
  { code: "ET", name: "Äthiopien", number: "231" },
  { code: "AU", name: "Australien", number: "036" },
  { code: "BS", name: "Bahamas", number: "044" },
  { code: "BH", name: "Bahrain", number: "048" },
  { code: "BD", name: "Bangladesch", number: "050" },
  { code: "BB", name: "Barbados", number: "052" },
  { code: "BY", name: "Belarus", number: "112" },
  { code: "BE", name: "Belgien", number: "056" },
  { code: "BZ", name: "Belize", number: "084" },
  { code: "BJ", name: "Benin", number: "204" },
  { code: "BM", name: "Bermuda", number: "060" },
  { code: "BT", name: "Bhutan", number: "064" },
  { code: "BO", name: "Bolivien", number: "068" },
  { code: "BA", name: "Bosnien und Herzegowina", number: "070" },
  { code: "BW", name: "Botsuana", number: "072" },
  { code: "BR", name: "Brasilien", number: "076" },
  { code: "BN", name: "Brunei Darussalam", number: "096" },
  { code: "BG", name: "Bulgarien", number: "100" },
  { code: "BF", name: "Burkina Faso", number: "854" },
  { code: "BI", name: "Burundi", number: "108" },
  { code: "CL", name: "Chile", number: "152" },
  { code: "CN", name: "China", number: "156" },
  { code: "CK", name: "Cookinseln", number: "184" },
  { code: "CR", name: "Costa Rica", number: "188" },
  { code: "DK", name: "Dänemark", number: "208" },
  { code: "DM", name: "Dominica", number: "212" },
  { code: "DO", name: "Dominikanische Republic", number: "214" },
  { code: "DJ", name: "Dschibuti", number: "262" },
  { code: "EC", name: "Ecuador", number: "218" },
  { code: "SV", name: "El Salvador", number: "222" },
  { code: "CI", name: "Elfenbeinküste", number: "384" },
  { code: "ER", name: "Eritrea", number: "232" },
  { code: "EE", name: "Estland", number: "233" },
  { code: "SZ", name: "Eswatini", number: "748" },
  { code: "FJ", name: "Fidschi", number: "242" },
  { code: "FI", name: "Finnland", number: "246" },
  { code: "GA", name: "Gabun", number: "266" },
  { code: "GM", name: "Gambia", number: "270" },
  { code: "GE", name: "Georgien", number: "268" },
  { code: "GH", name: "Ghana", number: "288" },
  { code: "GI", name: "Gibraltar", number: "292" },
  { code: "GD", name: "Grenada", number: "308" },
  { code: "GR", name: "Griechenland", number: "300" },
  { code: "GL", name: "Grönland", number: "304" },
  { code: "GU", name: "Guam", number: "316" },
  { code: "GT", name: "Guatemala", number: "320" },
  { code: "GN", name: "Guinea", number: "324" },
  { code: "GW", name: "Guinea-Bissau", number: "624" },
  { code: "GY", name: "Guyana", number: "328" },
  { code: "HT", name: "Haiti", number: "332" },
  { code: "HN", name: "Honduras", number: "340" },
  { code: "HK", name: "Hong Kong", number: "344" },
  { code: "IN", name: "Indien", number: "356" },
  { code: "ID", name: "Indonesien", number: "360" },
  { code: "IR", name: "Iran", number: "364" },
  { code: "IQ", name: "Irak", number: "368" },
  { code: "IE", name: "Irland", number: "372" },
  { code: "IS", name: "Island", number: "352" },
  { code: "IL", name: "Israel", number: "376" },
  { code: "IT", name: "Italien", number: "380" },
  { code: "JM", name: "Jamaika", number: "388" },
  { code: "JP", name: "Japan", number: "392" },
  { code: "YE", name: "Jemen", number: "887" },
  { code: "JO", name: "Jordanien", number: "400" },
  { code: "KH", name: "Kambodscha", number: "116" },
  { code: "CM", name: "Kamerun", number: "120" },
  { code: "CA", name: "Kanada", number: "124" },
  { code: "CV", name: "Kap Verde", number: "132" },
  { code: "KZ", name: "Kasachstan", number: "398" },
  { code: "KE", name: "Kenia", number: "404" },
  { code: "QA", name: "Katar", number: "634" },
  { code: "KG", name: "Kirgisistan", number: "417" },
  { code: "KI", name: "Kiribati", number: "296" },
  { code: "CO", name: "Kolumbien", number: "170" },
  { code: "KM", name: "Komoren", number: "174" },
  { code: "CD", name: "Kongo (Demokratische Republik)", number: "180" },
  { code: "CG", name: "Kongo (Republik)", number: "178" },
  { code: "KP", name: "Nordkorea", number: "408" },
  { code: "XK", name: "Kosovo", number: "383" },
  { code: "HR", name: "Kroatien", number: "191" },
  { code: "CU", name: "Kuba", number: "192" },
  { code: "KW", name: "Kuwait", number: "414" },
  { code: "LA", name: "Laos", number: "418" },
  { code: "LS", name: "Lesotho", number: "426" },
  { code: "LV", name: "Lettland", number: "428" },
  { code: "LB", name: "Libanon", number: "422" },
  { code: "LR", name: "Liberia", number: "430" },
  { code: "LY", name: "Libyen", number: "434" },
  { code: "LI", name: "Liechtenstein", number: "438" },
  { code: "LT", name: "Litauen", number: "440" },
  { code: "LU", name: "Luxemburg", number: "442" },
  { code: "MO", name: "Macau", number: "446" },
  { code: "MG", name: "Madagaskar", number: "450" },
  { code: "MW", name: "Malawi", number: "454" },
  { code: "MY", name: "Malaysia", number: "458" },
  { code: "MV", name: "Malediven", number: "462" },
  { code: "ML", name: "Mali", number: "466" },
  { code: "MT", name: "Malta", number: "470" },
  { code: "MA", name: "Marokko", number: "504" },
  { code: "MH", name: "Marshallinseln", number: "584" },
  { code: "MR", name: "Mauretanien", number: "478" },
  { code: "MU", name: "Mauritius", number: "480" },
  { code: "MX", name: "Mexiko", number: "484" },
  { code: "FM", name: "Mikronesien", number: "583" },
  { code: "MD", name: "Moldau", number: "498" },
  { code: "MC", name: "Monaco", number: "492" },
  { code: "MN", name: "Mongolei", number: "496" },
  { code: "ME", name: "Montenegro", number: "499" },
  { code: "MZ", name: "Mosambik", number: "508" },
  { code: "MM", name: "Myanmar", number: "104" },
  { code: "NA", name: "Namibia", number: "516" },
  { code: "NR", name: "Nauru", number: "520" },
  { code: "NP", name: "Nepal", number: "524" },
  { code: "NZ", name: "Neuseeland", number: "554" },
  { code: "NI", name: "Nicaragua", number: "558" },
  { code: "NL", name: "Niederlande", number: "528" },
  { code: "NE", name: "Niger", number: "562" },
  { code: "NG", name: "Nigeria", number: "566" },
  { code: "NU", name: "Niue", number: "570" },
  { code: "MK", name: "Nordmazedonien", number: "807" },
  { code: "NO", name: "Norwegen", number: "578" },
  { code: "OM", name: "Oman", number: "512" },
  { code: "AT", name: "Österreich", number: "040" },
  { code: "PK", name: "Pakistan", number: "586" },
  { code: "PS", name: "Palästina", number: "275" },
  { code: "PW", name: "Palau", number: "585" },
  { code: "PA", name: "Panama", number: "591" },
  { code: "PG", name: "Papua-Neuguinea", number: "598" },
  { code: "PY", name: "Paraguay", number: "600" },
  { code: "PE", name: "Peru", number: "604" },
  { code: "PH", name: "Philippinen", number: "608" },
  { code: "PL", name: "Polen", number: "616" },
  { code: "PT", name: "Portugal", number: "620" },
  { code: "PR", name: "Puerto Rico", number: "630" },
  { code: "RW", name: "Ruanda", number: "646" },
  { code: "RO", name: "Rumänien", number: "642" },
  { code: "RU", name: "Russland", number: "643" },
  { code: "SB", name: "Salomonen", number: "090" },
  { code: "ZM", name: "Sambia", number: "894" },
  { code: "WS", name: "Samoa", number: "882" },
  { code: "SM", name: "San Marino", number: "674" },
  { code: "ST", name: "São Tomé und Príncipe", number: "678" },
  { code: "SA", name: "Saudi Arabien", number: "682" },
  { code: "SE", name: "Schweden", number: "752" },
  { code: "SN", name: "Senegal", number: "686" },
  { code: "RS", name: "Serbien", number: "688" },
  { code: "SC", name: "Seychellen", number: "690" },
  { code: "SL", name: "Sierra Leone", number: "694" },
  { code: "ZW", name: "Simbabwe", number: "716" },
  { code: "SG", name: "Singapur", number: "702" },
  { code: "SK", name: "Slowakei", number: "703" },
  { code: "SI", name: "Slowenien", number: "705" },
  { code: "SO", name: "Somalia", number: "706" },
  { code: "ES", name: "Spanien", number: "724" },
  { code: "LK", name: "Sri Lanka", number: "144" },
  { code: "KN", name: "St. Kitts und Nevis", number: "659" },
  { code: "LC", name: "St. Lucia", number: "662" },
  { code: "VC", name: "St. Vincent und die Grenadinen", number: "670" },
  { code: "ZA", name: "Südafrika", number: "710" },
  { code: "SD", name: "Sudan", number: "729" },
  { code: "KR", name: "Südkorea", number: "410" },
  { code: "SS", name: "Südsudan", number: "728" },
  { code: "SR", name: "Suriname", number: "740" },
  { code: "SY", name: "Syrien", number: "760" },
  { code: "TJ", name: "Tadschikistan", number: "762" },
  { code: "TZ", name: "Tanzania", number: "834" },
  { code: "TW", name: "Taiwan", number: "158" },
  { code: "TH", name: "Thailand", number: "764" },
  { code: "TG", name: "Togo", number: "768" },
  { code: "TO", name: "Tonga", number: "776" },
  { code: "TT", name: "Trinidad und Tobago", number: "780" },
  { code: "TD", name: "Tschad", number: "148" },
  { code: "CZ", name: "Tschechien", number: "203" },
  { code: "TN", name: "Tunesien", number: "788" },
  { code: "TR", name: "Türkei", number: "792" },
  { code: "TM", name: "Turkmenistan", number: "795" },
  { code: "TV", name: "Tuvalu", number: "798" },
  { code: "UG", name: "Uganda", number: "800" },
  { code: "UA", name: "Ukraine", number: "804" },
  { code: "HU", name: "Ungarn", number: "348" },
  { code: "UY", name: "Uruguay", number: "858" },
  { code: "UZ", name: "Usbekistan", number: "860" },
  { code: "VU", name: "Vanuatu", number: "548" },
  { code: "VA", name: "Vatikanstadt", number: "336" },
  { code: "VE", name: "Venezuela", number: "862" },
  { code: "AE", name: "Vereinigte Arabische Emirate", number: "784" },
  { code: "US", name: "Vereinigte Staaten", number: "840" },
  { code: "GB", name: "Vereinigtes Königreich", number: "826" },
  { code: "VN", name: "Vietnam", number: "704" },
  { code: "EH", name: "Westsahara", number: "732" },
  { code: "CF", name: "Zentralafrikanische Republik", number: "140" },
  { code: "CY", name: "Zypern", number: "196" }
];
